"""mcp_common — MCP 자산(4번째 kind) 의 순수 로직: spec 파싱 · 직렬화 · 시크릿 문법.

generate(_gen_mcp) 와 validate(_validate_mcp) 가 공유한다. IO 최소(spec 읽기만), 직렬화·검사는 순수.
설계 정본 plan_docs/mcp-asset-kind-plan.md (codex R1/R2 반영):
- payload SSOT = spec md frontmatter (profile 아님). pyyaml 로 파싱(hook regex 파서 재사용 금지).
- 직렬화: claude→.mcp.json(JSON) / codex→.codex/config.toml managed-block(TOML). 결정론(byte-stable).
- 시크릿: env 는 변수명만, 생성 시 ${VAR} placeholder. 리터럴 시크릿은 hash 전에 거부(FAIL).
"""
import json
import os
import re
from pathlib import Path

CONTRACT_VERSION = "1"

MCP_TRANSPORTS = ("stdio", "http", "sse")
_REMOTE_TRANSPORTS = ("http", "sse")

# .codex/config.toml 안에서 SAGE 가 소유하는 managed-block 마커 (블록 밖은 보존).
CODEX_BLOCK_START = "# >>> SAGE MCP START (generated by sage generate — do not edit)"
CODEX_BLOCK_END = "# <<< SAGE MCP END"

# env 변수명 규약: 대문자/숫자/언더스코어 식별자. 값(=·공백·특수문자)은 불허(리터럴 시크릿 차단).
_ENV_NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
# 서버 id 규약: 영숫자/언더스코어/하이픈만 (점 금지 — TOML 중첩테이블 오인 방지, codex R3 P1).
_SERVER_ID_RE = re.compile(r"^[A-Za-z0-9_\-]+$")
# 시크릿 컨텍스트 플래그(인접 인자에 시크릿이 올 신호): --token / --api-key / Authorization: 등.
# ★ codex R4: 양끝 앵커 — 'oauth' 가 'auth' 접미사로 오탐되던 것 차단(인자 전체가 플래그여야 매칭).
_SECRET_FLAG_RE = re.compile(r"(?i)^(--?)?(api[_\-]?key|token|secret|authorization|auth|password|passwd|bearer):?$")
# 고엔트로피 토큰(단독=WARN, key=/token=/auth 동반=FAIL) — 길이 20+ 영숫자 혼합.
_HI_ENTROPY_RE = re.compile(r"(?=[A-Za-z0-9_\-]{20,})(?=.*[A-Za-z])(?=.*[0-9])[A-Za-z0-9_\-]{20,}")
_SECRET_CONTEXT_RE = re.compile(r"(?i)(key|token|secret|auth|password|passwd|bearer)\s*[=:]")
_USERINFO_RE = re.compile(r"^[a-zA-Z][a-zA-Z0-9+.\-]*://[^/@\s]+:[^/@\s]+@")  # scheme://user:pass@
_URL_TOKEN_QUERY_RE = re.compile(r"(?i)[?&](token|key|access_token|api_key|secret)=")
_HOME_PATH_RE = re.compile(r"/(?:Users|home)/[^/\s]+")


class MCPSpecError(Exception):
    """spec frontmatter 파싱/구조 오류 (generate 가 FAIL 로 변환)."""


def parse_mcp_spec(spec_path):
    """docs/sage_harness/mcps/{id}.md → 구조화 dict (pyyaml frontmatter).

    반환: {id, transport, runtime_targets:[...], server_binding:{...}}.
    frontmatter 누락/YAML 오류/필수필드 누락/미지원 transport → MCPSpecError.
    """
    try:
        import yaml
    except ImportError as e:
        raise MCPSpecError("pyyaml 미설치 (generate 빌드 의존성) — pip install pyyaml") from e
    text = Path(spec_path).read_text(encoding="utf-8")
    # CRLF/구분자 뒤 공백 허용(codex R3 P2 — 이식성). 본문의 '---' 는 non-greedy 로 첫 닫힘만.
    m = re.match(r"^---[ \t]*\r?\n(.*?)\r?\n---[ \t]*\r?\n", text, re.DOTALL)
    if not m:
        raise MCPSpecError(f"frontmatter 없음: {spec_path}")
    try:
        fm = yaml.safe_load(m.group(1)) or {}
    except Exception as e:
        raise MCPSpecError(f"frontmatter YAML 파싱 실패: {e}") from e
    if not isinstance(fm, dict):
        raise MCPSpecError("frontmatter 가 매핑이 아님")
    sid = fm.get("id")
    transport = fm.get("transport")
    targets = fm.get("runtime_targets") or []
    binding = fm.get("server_binding") or {}
    if not sid or not isinstance(sid, str):
        raise MCPSpecError("id 누락/문자열 아님")
    if not _SERVER_ID_RE.match(sid):
        raise MCPSpecError(f"id {sid!r} 부적합 — 영숫자/_/- 만 허용(점·공백 금지: TOML 중첩테이블 오인 방지)")
    if transport not in MCP_TRANSPORTS:
        raise MCPSpecError(f"미지원 transport: {transport!r} (허용: {', '.join(MCP_TRANSPORTS)})")
    if not isinstance(targets, list) or not targets:
        raise MCPSpecError("runtime_targets 가 비었거나 리스트가 아님")
    for t in targets:
        if t not in ("claude", "codex"):
            raise MCPSpecError(f"미지원 runtime_target: {t!r}")
    if not isinstance(binding, dict):
        raise MCPSpecError("server_binding 이 매핑이 아님")
    # args/env 타입 강제 (codex R3 P1 — 문자열을 리스트로 오인해 문자분해 직렬화되는 것 방지)
    args = binding.get("args")
    if args is not None:
        if not isinstance(args, list) or any(not isinstance(a, (str, int, float, bool)) for a in args):
            raise MCPSpecError("server_binding.args 는 스칼라 리스트여야 함(문자열 단일값 금지)")
    env = binding.get("env")
    if env is not None:
        if not isinstance(env, list) or any(not isinstance(e, str) for e in env):
            raise MCPSpecError("server_binding.env 는 문자열(변수명) 리스트여야 함")
    if transport == "stdio":
        if not binding.get("command") or not isinstance(binding["command"], str):
            raise MCPSpecError("stdio transport 는 server_binding.command(문자열) 필수")
    else:  # http/sse
        if not binding.get("url") or not isinstance(binding["url"], str):
            raise MCPSpecError(f"{transport} transport 는 server_binding.url(문자열) 필수")
    return {"id": sid, "transport": transport,
            "runtime_targets": list(targets), "server_binding": binding}


def check_secrets(model):
    """spec 모델의 시크릿 거부 문법 → [(sev, msg)] (FAIL/WARN). 빈 리스트=깨끗.

    FAIL(거부): env 값-형 토큰 / args 의 key=·token=·Bearer 동반 고엔트로피 / url userinfo·token-query.
    WARN(표시): 고엔트로피 토큰 단독(오탐 회피) / command·args 의 홈경로 username 누출.
    """
    issues = []
    b = model["server_binding"]
    # env: 변수명만 허용 (리터럴 값 차단)
    for name in (b.get("env") or []):
        if not isinstance(name, str) or not _ENV_NAME_RE.match(name):
            issues.append(("FAIL", f"env 항목 '{name}' 은 변수명이 아님 — 변수명만 허용(리터럴 값 금지)"))
    # args 검사 (same-arg 컨텍스트 + split-arg 인접 컨텍스트 둘 다 — codex R3 P1)
    args = [str(a) for a in (b.get("args") or [])]
    prev_is_flag = False
    for s in args:
        same_arg_secret = _SECRET_CONTEXT_RE.search(s) and _HI_ENTROPY_RE.search(s)
        bearer = re.search(r"(?i)bearer\s+\S{8,}", s)
        if same_arg_secret or bearer:
            issues.append(("FAIL", f"args 에 인라인 시크릿 의심(key/token/auth + 고엔트로피): {_redact(s)}"))
        elif prev_is_flag and _HI_ENTROPY_RE.search(s):
            # 직전 인자가 시크릿 플래그(--token 등)이고 이 인자가 고엔트로피 → split 형태 시크릿
            issues.append(("FAIL", f"args 에 split 인라인 시크릿 의심(시크릿 플래그 뒤 고엔트로피): {_redact(s)}"))
        elif _HI_ENTROPY_RE.search(s):
            issues.append(("WARN", f"args 에 고엔트로피 토큰(단독 — 시크릿일 수 있음 확인): {_redact(s)}"))
        if _HOME_PATH_RE.search(s):
            issues.append(("WARN", f"args 에 홈경로 username 누출(이식성): {s}"))
        prev_is_flag = bool(_SECRET_FLAG_RE.search(s))
    # command 홈경로
    cmd = b.get("command")
    if cmd and _HOME_PATH_RE.search(str(cmd)):
        issues.append(("WARN", f"command 에 홈경로 username 누출(이식성): {cmd}"))
    # url userinfo / token-query
    url = b.get("url")
    if url:
        if _USERINFO_RE.search(str(url)):
            issues.append(("FAIL", f"url 에 userinfo(user:pass@) 포함: {_redact(str(url))}"))
        if _URL_TOKEN_QUERY_RE.search(str(url)):
            issues.append(("FAIL", f"url 쿼리에 token/key 포함: {_redact(str(url))}"))
    return issues


def _redact(s):
    """메시지 출력 시 고엔트로피 토큰을 가린다(로그 누출 2차 방지)."""
    return _HI_ENTROPY_RE.sub("***", str(s))


def _claude_entry(model):
    """spec 모델 → .mcp.json mcpServers[id] 엔트리 (placeholder-preserving)."""
    b = model["server_binding"]
    if model["transport"] == "stdio":
        e = {"command": b["command"]}
        if b.get("args"):
            e["args"] = list(b["args"])
        if b.get("env"):
            e["env"] = {n: "${" + n + "}" for n in b["env"]}
        return e
    e = {"type": model["transport"], "url": b["url"]}
    if b.get("env"):
        e["env"] = {n: "${" + n + "}" for n in b["env"]}
    return e


def serialize_claude(models):
    """claude-target spec 모델들 → .mcp.json 문자열 (결정론: id 정렬, indent=2)."""
    servers = {}
    for mdl in models:
        if "claude" in mdl["runtime_targets"]:
            servers[mdl["id"]] = _claude_entry(mdl)
    doc = {"mcpServers": {k: servers[k] for k in sorted(servers)}}
    return json.dumps(doc, ensure_ascii=False, indent=2) + "\n"


def _toml_str(s):
    """TOML 기본 문자열 리터럴(결정론 escape)."""
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def _toml_arr(items):
    return "[" + ", ".join(_toml_str(i) for i in items) + "]"


def _codex_server_toml(model):
    """spec 모델 → [mcp_servers.<id>] TOML 조각 (결정론)."""
    b = model["server_binding"]
    sid = model["id"]
    lines = [f"[mcp_servers.{sid}]"]
    if model["transport"] == "stdio":
        lines.append(f"command = {_toml_str(b['command'])}")
        if b.get("args"):
            lines.append(f"args = {_toml_arr(b['args'])}")
    else:
        lines.append(f"url = {_toml_str(b['url'])}")
    if b.get("env"):
        lines.append(f"[mcp_servers.{sid}.env]")
        for n in b["env"]:
            lines.append(f"{n} = {_toml_str('${' + n + '}')}")
    return "\n".join(lines)


def serialize_codex_block(models):
    """codex-target spec 모델들 → managed-block 문자열 (마커 포함, id 정렬). 빈 모델 → 마커만."""
    codex_models = sorted((m for m in models if "codex" in m["runtime_targets"]),
                          key=lambda m: m["id"])
    body = "\n\n".join(_codex_server_toml(m) for m in codex_models)
    inner = (body + "\n") if body else ""
    return f"{CODEX_BLOCK_START}\n{inner}{CODEX_BLOCK_END}\n"


def replace_codex_block(existing_text, block):
    """기존 config.toml 텍스트에서 managed-block 만 교체(없으면 append). 블록 밖 보존.

    반환: (new_text, error). error 는 마커가 중복/malformed 일 때 메시지(None=정상).
    """
    starts = existing_text.count(CODEX_BLOCK_START)
    ends = existing_text.count(CODEX_BLOCK_END)
    if starts > 1 or ends > 1:
        return existing_text, "managed-block 마커 중복"
    if (starts == 1) != (ends == 1):
        return existing_text, "managed-block 마커 짝 불일치(malformed)"
    if starts == 0:
        sep = "" if existing_text.endswith("\n") or not existing_text else "\n"
        joiner = "\n" if existing_text else ""
        return existing_text + sep + joiner + block, None
    pat = re.compile(re.escape(CODEX_BLOCK_START) + r".*?" + re.escape(CODEX_BLOCK_END) + r"\n?",
                     re.DOTALL)
    return pat.sub(block, existing_text, count=1), None


def extract_codex_block(text):
    """config.toml 텍스트에서 managed-block 문자열 추출(없으면 None). render_hash 계산원."""
    m = re.search(re.escape(CODEX_BLOCK_START) + r".*?" + re.escape(CODEX_BLOCK_END) + r"\n?",
                  text, re.DOTALL)
    return m.group(0) if m else None


def codex_servers_outside_block(text):
    """managed-block '밖'에 선언된 [mcp_servers.<name>] 의 이름 목록(소유권 충돌 탐지)."""
    block = extract_codex_block(text) or ""
    outside = text.replace(block, "") if block else text
    return sorted(set(re.findall(r"^\[mcp_servers\.([A-Za-z0-9_\-]+)\]", outside, re.MULTILINE)))


def codex_servers_inside_block(text):
    """managed-block '안'에 선언된 [mcp_servers.<name>] 이름 목록.

    ★ codex R5 P1: 블록은 SAGE 전적 소유 → 선언 서버만 있어야 함. 여기서 얻은 집합이 manifest 의
    codex-target 집합을 초과하면 주입/변조(validate FAIL). 파서 우선, 미가용 시 정규식 폴백."""
    block = extract_codex_block(text)
    if not block:
        return []
    inner = _strip_block_markers(block)
    parser = _toml_parser()
    if parser is None:
        return sorted(set(re.findall(r"^\[mcp_servers\.([A-Za-z0-9_\-]+)\]", inner, re.MULTILINE)))
    try:
        return sorted((parser.loads(inner).get("mcp_servers") or {}).keys())
    except Exception:
        # 파싱 실패해도 정규식으로 최대한 표면화(침묵 통과 방지)
        return sorted(set(re.findall(r"^\[mcp_servers\.([A-Za-z0-9_\-]+)\]", inner, re.MULTILINE)))


def verify_toml(text):
    """생성된 TOML 유효성 검증 → (ok, note). py3.11+ tomllib / py<3.11 tomli / 둘 다 없으면 best-effort skip."""
    parser = _toml_parser()
    if parser is None:
        return True, "tomllib/tomli 미가용 — TOML 검증 skip(best-effort)"
    try:
        parser.loads(text)
        return True, None
    except Exception as e:
        return False, f"TOML 파싱 실패: {e}"


def canonical_render(model, target):
    """target 별 per-server canonical 직렬화 문자열 (render_hash 계산원).

    per-server 라 다른 서버 변경이 이 서버의 render_hash 를 흔들지 않음(false-STALE 방지, codex R2).
    """
    if target == "claude":
        return json.dumps(_claude_entry(model), ensure_ascii=False, sort_keys=True)
    return _codex_server_toml(model)


def actual_claude_canonical(mcp_json_text, sid):
    """실제 .mcp.json 의 server 엔트리를 canonical_render(claude)와 동일 형식으로 직렬화 → str|None.

    validate 가 spec 재계산값 대신 '실제 산출물'과 대조해 산출물 직접편집 드리프트를 잡는다(codex R3 P0)."""
    try:
        doc = json.loads(mcp_json_text)
    except Exception:
        return None
    servers = (doc.get("mcpServers") or {}) if isinstance(doc, dict) else {}
    if sid not in servers:
        return None
    return json.dumps(servers[sid], ensure_ascii=False, sort_keys=True)


def _toml_parser():
    """py3.11+ tomllib / py<3.11 tomli / 둘 다 없으면 None."""
    try:
        import tomllib as t
        return t
    except ImportError:
        try:
            import tomli as t
            return t
        except ImportError:
            return None


def _strip_block_markers(block_text):
    """managed-block 의 마커 주석 줄을 제거한 내부 TOML 만 반환."""
    return "\n".join(ln for ln in (block_text or "").splitlines()
                     if not ln.startswith("# >>> SAGE MCP") and not ln.startswith("# <<< SAGE MCP"))


def codex_block_has_server(block_text, model):
    """managed-block 안의 이 서버 정의가 spec 기대와 구조적으로 일치하는지 → bool.

    ★ codex R4 P0: substring 이 아니라 **TOML 파싱 후 구조 비교**(multiline 문자열 안에 조각을 숨겨
    실제 서버는 변조하는 우회 차단). 파서 미가용(py3.10 무 tomli) 시에만 substring 폴백(best-effort)."""
    parser = _toml_parser()
    if parser is None:
        return _codex_server_toml(model) in (block_text or "")
    sid = model["id"]
    try:
        actual = (parser.loads(_strip_block_markers(block_text)).get("mcp_servers") or {}).get(sid)
        expected = (parser.loads(_codex_server_toml(model)).get("mcp_servers") or {}).get(sid)
    except Exception:
        return False
    return actual is not None and actual == expected


def list_mcp_specs(root):
    """docs/sage_harness/mcps/*.md 의 id 목록 (orphan 탐지·전체생성용)."""
    d = os.path.join(root, "docs", "sage_harness", "mcps")
    if not os.path.isdir(d):
        return []
    return sorted(fn[:-3] for fn in os.listdir(d) if fn.endswith(".md"))
